#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

#!/usr/bin/env sh

# bar settings
yabai -m config top_padding 0

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus

yabai -m config window_placement             second_child
yabai -m config window_topmost               off

yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on

yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off

# Mouse support
yabai -m config mouse_modifier               alt
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config bottom_padding               0
yabai -m config left_padding                 0
yabai -m config right_padding                0
yabai -m config window_gap                   0

# float system preferences
yabai -m rule --add app='^System Information$' manage=off
yabai -m rule --add app='^System Preferences$' manage=off
yabai -m rule --add title='Preferences$' manage=off

# lol
yabai -m rule --add app='League of Legends' manage=off
yabai -m rule --add app='Riot' manage=off

# float settings windows
yabai -m rule --add app='Settings$' manage=off

# Some IDEA settings
yabai -m rule --add app='.*IDEA.*' title='^$' manage=off
yabai -m rule --add app='.*IDEA.*' title='Project Structure' manage=off
yabai -m rule --add app='.*IDEA.*' title='Preferences' manage=off
yabai -m rule --add app='.*IDEA.*' title='Edit configuration' manage=off

# Okta
yabai -m rule --add app='Okta Verify' manage=off

# VMware
yabai -m rule --add app='VMware Fusion' manage=off

# spacebar padding on top screen
SPACEBAR_HEIGHT=$(spacebar -m config height)
yabai -m config external_bar all:$SPACEBAR_HEIGHT:0

# spaces
yabai -m space 1 --label term
yabai -m space 2 --label web
yabai -m space 3 --label code
yabai -m space 4 --label 4
yabai -m space 5 --label social
yabai -m space 6 --label 6
yabai -m space 7 --label notes
yabai -m space 8 --label media

yabai -m rule --add app="Arc" space=^web
yabai -m rule --add app="Google Chrome" space=^web
yabai -m rule --add app="alacritty" space=^term
yabai -m rule --add app=".*IDEA.*" space=^code
yabai -m rule --add app="PhpStorm" space=^code
yabai -m rule --add app="WebStorm" space=^code
yabai -m rule --add app="code" space=^code
yabai -m rule --add app="Slack" space=^social
yabai -m rule --add app="Obsidian" space=^notes
yabai -m rule --add app="Notion" space=^notes
yabai -m rule --add app="Spotify" space=^media

echo "yabai configuration loaded.."
